package com.school.app.platform;

public enum AuditAction {
    SIGNUP_REQUEST_APPROVED,
    SIGNUP_REQUEST_REJECTED,
    SCHOOL_STATUS_CHANGED,
    SUBSCRIPTION_PLAN_CHANGED,
    TRIAL_SELF_PROVISIONED,
    PLATFORM_SETTINGS_UPDATED,
    PAYMENT_VERIFIED,
    PAYMENT_REJECTED,
    SUBSCRIPTION_MARKED_PAST_DUE
}
